[project]
name = "example-mcp-server"
version = "0.1.0"
description = "Example MCP server demonstrating basic functionality"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
   "mcp>=1.9.3",
   "pydantic>=2.11.3",
   "aiohttp>=3.8.0",
]